### ISSUE TITLE
[Core] Game Manager Implementation

### ISSUE THREAD

**Issue by markoub** [markoub/shape-sorter-adventures#3]
## Overview
Implement the core Game Manager system that will handle the game's main logic, state management, and flow control.

## Requirements
- Implement singleton pattern for game manager
- Handle game states (Menu, Playing, Paused, GameOver)
- Manage level progression
- Handle score system
- Implement save/load functionality
- Track player progress

### Game States
```csharp
public enum GameState
{
    Menu,
    Playing,
    Paused,
    GameOver
}
```

### Level Structure
```csharp
[System.Serializable]
public class Level
{
    public ShapeType[] requiredPattern;
    public int targetScore;
    public float timeLimit;
    public int difficulty;
}
```

### Required Methods
- InitializeGame()
- StartLevel(int levelIndex)
- PauseGame()
- ResumeGame()
- EndGame()
- SaveProgress()
- LoadProgress()
- UpdateScore(int points)
- CheckWinCondition()

## Tasks
1. Create GameManager class with singleton pattern
2. Implement state machine for game states
3. Create level management system
4. Implement score tracking
5. Add save/load functionality using PlayerPrefs
6. Create event system for game state changes
7. Implement pause functionality
8. Add level progression logic

## Definition of Done
- [ ] GameManager successfully controls game flow
- [ ] All game states work correctly
- [ ] Level progression works as expected
- [ ] Score system functions properly
- [ ] Save/Load functionality works
- [ ] Pause system works correctly
- [ ] Unit tests for core functionality pass
- [ ] No errors in console during state transitions

## Integration Points
- UI System
- Level System
- Save System
- Audio Manager
- Input Manager

## Notes
- Consider adding analytics hooks
- Plan for future extensibility
- Document all public methods and properties
- Include error handling for edge cases
