### ISSUE TITLE
[Gameplay] Level System Implementation

### ISSUE THREAD

**Issue by markoub** [markoub/shape-sorter-adventures#6]
## Overview
Design and implement the level system for Shape Sorter Adventures, including level progression, difficulty scaling, and educational content integration.

## Requirements
- Level data structure
- Progressive difficulty system
- Level loading/unloading
- Level completion criteria
- Tutorial levels
- Reward system
- Educational content integration
- Level analytics

### Level Data Structure
```csharp
[System.Serializable]
public class LevelData
{
    public int levelId;
    public string levelName;
    public DifficultyTier difficulty;
    public ShapePattern[] patterns;
    public float timeLimit;
    public int targetScore;
    public string[] educationalHints;
    public RewardData rewards;
}

public enum DifficultyTier
{
    Tutorial,
    Easy,
    Medium,
    Hard,
    Challenge
}
```

## Level Design Guidelines
1. Tutorial Levels (1-3):
   - Single shape matching
   - Basic drag and drop
   - Simple patterns
   - Unlimited time

2. Easy Levels (4-10):
   - 2-3 shapes
   - Basic patterns
   - Generous time limits
   - Simple matching

3. Medium Levels (11-20):
   - 3-4 shapes
   - Complex patterns
   - Moderate time limits
   - Multiple objectives

4. Hard Levels (21-30):
   - 4-5 shapes
   - Advanced patterns
   - Strict time limits
   - Multiple objectives

## Tasks
1. Create LevelManager class
2. Implement level loading system
3. Create difficulty progression
4. Design tutorial levels
5. Implement level completion logic
6. Add reward system
7. Create level selection menu
8. Implement level analytics
9. Add educational content
10. Create level editor tools

## Definition of Done
- [ ] Levels load correctly
- [ ] Difficulty progression works smoothly
- [ ] Tutorial levels are clear and helpful
- [ ] Level completion criteria work correctly
- [ ] Rewards are properly awarded
- [ ] Educational content is age-appropriate
- [ ] Analytics are properly tracked
- [ ] Level editor tools work correctly

## Educational Integration
- Shape recognition skills
- Pattern matching
- Basic geometry concepts
- Problem-solving skills
- Time management
- Memory development

## Level Editor Requirements
- Visual level editor
- Pattern creator
- Difficulty settings
- Time limit adjustment
- Educational content input
- Reward configuration
- Testing tools

## Notes
- Include progress saving
- Consider memory management
- Plan for future level packs
- Include level randomization
- Add difficulty adjustment system
- Document level design patterns
- Include educational metrics
- Consider localization needs
