### ISSUE TITLE
[Core] Save System Implementation

### ISSUE THREAD

**Issue by markoub** [markoub/shape-sorter-adventures#8]
## Overview
Implement a robust save system that handles player progress, settings, and achievements while ensuring data persistence across sessions.

## Requirements
- Player progress tracking
- Settings persistence
- Achievement system
- Cloud save support
- Data encryption
- Backup system
- Cross-platform compatibility
- Parent controls persistence

### Save Data Structure
```csharp
[System.Serializable]
public class GameSaveData
{
    public PlayerProgress playerProgress;
    public GameSettings gameSettings;
    public AchievementData achievements;
    public ParentControlSettings parentControls;
    public string lastSaveDate;
    public string gameVersion;
}

[System.Serializable]
public class PlayerProgress
{
    public int currentLevel;
    public int[] levelScores;
    public int[] levelStars;
    public float totalPlayTime;
    public Dictionary<string, bool> unlockedContent;
    public List<TutorialProgress> completedTutorials;
}

[System.Serializable]
public class GameSettings
{
    public float masterVolume;
    public float musicVolume;
    public float sfxVolume;
    public float voiceVolume;
    public bool subtitlesEnabled;
    public bool highContrastMode;
    public string language;
    public AccessibilitySettings accessibility;
}
```

### Save Management
- Auto-save system
- Manual save points
- Save file versioning
- Save file validation
- Corrupted save recovery
- Save file migration

### Cloud Integration
- Cloud save synchronization
- Conflict resolution
- Offline mode handling
- Data compression
- Bandwidth optimization

### Security
- Data encryption
- Save file validation
- Anti-tampering measures
- Secure storage access
- Privacy compliance

## Tasks
1. Create SaveManager class
2. Implement local save system
3. Add cloud save support
4. Create data encryption system
5. Implement auto-save
6. Add save file validation
7. Create backup system
8. Implement settings persistence
9. Add achievement tracking
10. Create save migration system

## Save File Locations
- Windows: %AppData%/ShapeSorterAdventures/
- macOS: ~/Library/Application Support/ShapeSorterAdventures/
- Android: Application.persistentDataPath
- iOS: Application.persistentDataPath
- WebGL: PlayerPrefs/IndexedDB

## Definition of Done
- [ ] Save system works reliably
- [ ] Cloud saves function correctly
- [ ] Data encryption is implemented
- [ ] Auto-save works as expected
- [ ] Settings persist between sessions
- [ ] Save files can be backed up
- [ ] Save migration works
- [ ] Offline mode functions
- [ ] Data validation is robust
- [ ] Privacy compliance is ensured

## Data Security
- Encryption key management
- Secure storage access
- Data integrity checks
- Privacy compliance
- COPPA compliance
- GDPR considerations

## Error Handling
- Corrupted save detection
- Automatic backup creation
- Recovery procedures
- Error logging
- User notifications
- Fallback mechanisms

## Notes
- Consider save file size
- Implement versioning system
- Plan for future expansions
- Document save file structure
- Include debugging tools
- Consider platform limitations
- Plan for data migration
- Test edge cases
- Consider offline scenarios
- Document recovery procedures
